# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskboard
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
