spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskboard}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

server:
  port: 8081
  servlet:
    contextPath: /
